# Generated by Django 3.2 on 2021-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('slug_shortcut', models.CharField(max_length=100)),
                ('slug_url', models.SlugField(unique=True)),
            ],
        ),
    ]
